- name: configure backend server
  hosts: backend
  become: yes
  vars_files:
  - /var/expense/credentials_mysql.yaml
  roles:
  - backend          # go to roles folder and import all present in backend folder
